### PR TITLE
The homepage now lists 2.0.5 as the latest version.

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Comment by niden** [comment]
Thank you!

**Comment by SidRoberts** [comment]
@niden The JS and CSS have stopped working. It looks like `$config->application->debug` is `true` and the CDN URL points to `$config->application->baseUri` instead of `$config->application->cdn`.

**Comment by niden** [comment]
It is OK now. The baseUri was set to /website/. I need to remove the config file from github so that every time we pull does not break the site.

**Comment by sergeyklay** [comment]
@niden @SidRoberts This can be automated by using github api and phalcon repo releases

**Pull request merged**
