### PR TITLE
Adds the correct flag for Vietnam

### PR DESCRIPTION
**Pull request by Green-Cat**
Ref phalcon/cphalcon#10860

### CODE REVIEW

**Comment by phalcon** [comment]
Thanks

**Comment by vanquang9387** [comment]
@phalcon 
Actually, this problem has not been fixed.
**\<li\>**s are rendered by view vars:
````
<li role="presentation" class="dropdown-link">{{ languages_available }}</li>
```
and in `app/controllers/ControllerBase.php`:
```
$languagesAvailable .= "<a role='menuitem' tabindex='-1' href='{$href}' class='flag-{$key}'>{$value}</a>";
```
For Vietnam, the class will be `class="flag-vi"` which will cause using `vi.gif` file. But the right image for Vietnam is `vn.gif`.
The problem is you are using **country code** to name image files but using **language code** for classes.
**Country code** of **Vietnam** is **vn**.
**Language code** of **Vietnam** is **vi** which is the same as **country code** of **Virgin Islands**.
That will result in `class="flag-vi"` (for Vietnamese) will use `vi.gif` flag image of Virgin Islands :smile: 

It's confusing but hope you can understand.

**Comment by sergeyklay** [comment]
@vanquang9387 Can you please create PR?

**Comment by vanquang9387** [comment]
@sergeyklay I suggest removing flag icon. Because flags do not symbolize languages.
Refs:
http://flagsarenotlanguages.com/blog/
[Language menus: Flags symbolize nations, not languages](http://flagsarenotlanguages.com/blog/2013/08/language-menus-flags-symbolize-nations-not-languages/)

**Comment by sergeyklay** [comment]
@andresgutierrez

**Pull request merged**
