### PR TITLE
add more air to h1 

### PR DESCRIPTION
**Pull request by Arhell**
removed this file to make it easier to edit

### CODE REVIEW

**Comment by CameronHall** [comment]
@Arhell do we really want to remove the minimised file? Can't you just minify the CSS afterwards?

**Comment by ruudboon** [comment]
We should deploy minimized files, but maybe we can do it in the deployment process?

**Comment by Arhell** [comment]
I upd PR, add only air to h1

**Comment by niden** [comment]
Thank you @Arhell

**Pull request merged**
