### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by ovr** [comment]
ping @andresgutierrez

**Comment by andresgutierrez** [comment]
Why upload this to the website?

**Comment by ovr** [comment]
> Why upload this to the website?
Mmm?

**Comment by ovr** [comment]
Vagrant is needed to develop this project
All next commits is a fixes or refactoring

**Comment by andresgutierrez** [comment]
Why vagrant is needed to develop this project?

**Comment by ovr** [comment]
For example
I don't have any web software to run this site and not interest to do this manually
Vagrant is the easiest way to help contribute project

You can say

> Ok Dmitry you can use docker

but I am using OSX & boot2docker is not okey via virtual machine for LXC containers

Maybe some one else will be interest to contribute it, and via vagrant up the bootstrapping step will takes 5m automatic job to start working on project

**Pull request merged**
