### PR TITLE
Update DCT Host

### PR DESCRIPTION
**Pull request by HarryLee186**

### CODE REVIEW

**Comment by niden** [comment]
@HarryLee186 Are you going to upload a new image as per our discussion?

**Comment by HarryLee186** [comment]
Planning to this weekend, sorry for the delay

**Comment by HarryLee186** [comment]
Hi @niden , PR opened here regarding the new logo: https://github.com/phalcon/website/pull/523

Going to start drafting up a blog post so I'll let you know how it goes if I manage to go anywhere with it.

Cheers!

**Comment by CameronHall** [comment]
Thank you @HarryLee186

**Pull request merged**
