### PR TITLE
Correct language title for Vietnamese

### PR DESCRIPTION
**Pull request by vanquang9387**
Correct language title for Vietnamese

### CODE REVIEW

**Comment by sergeyklay** [comment]
Check please
```volt
{{ languages_available }}
```

**Comment by vanquang9387** [comment]
@sergeyklay Update the label "Việt" to "Tiếng Việt" in config.

**Comment by vanquang9387** [comment]
ping @sergeyklay

**Comment by sergeyklay** [comment]
@duythien is this OK to merge?

**Comment by vanquang9387** [comment]
You can check yourself here:
https://www.google.com.vn/?gws_rd=ssl


http://www.microsoft.com/en-us/locale.aspx

**Comment by duythien** [comment]
@sergeyklay that is ok :)

**Comment by sergeyklay** [comment]
Thanks

**Comment by vanquang9387** [comment]
Thanks. Didn't think that this tiny fix takes this long :smile:

**Pull request merged**
